import type { CadDefaults, LensProject, MeasurementsState, TargetLook } from "@/types";
import { defaultFocusTravelSetup } from "@/lib/focusTravel";

export const defaultCadDefaults: CadDefaults = {
  printToleranceMm: 0.18,
  glassSeatDiametralClearanceMm: 0.5,
  internalStepChamferMm: 0.3,
  radialClearanceMm: 0.15,
  wallThicknessMm: 2,
  retainingLipMm: 0.8,
  partThicknessMm: 2,
  screwDiameterMm: 2,
  camPinDiameterMm: 2,
  camSlotClearanceMm: 0.3,
  defaultOuterDiameterMm: 50,
  defaultInnerDiameterMm: 40,
  facets: 128,
  plStepReferencePath: "cad/reference/PL_Lens_Tail.STEP",
  plRearNeckOuterDiameterMm: 31.0,
  plRearNeckInnerDiameterMm: 26.0,
  plRearNeckLengthMm: 12.0,
  plLockingClearanceLengthMm: 12.0,
  plLockingClearanceDiameterMm: 42.0,
  plMainBarrelOuterDiameterMm: 44.0,
  plMainBarrelInnerDiameterMm: 40.0,
  plMainBarrelLengthMm: 48.0,
  plStepUpStartFromFlangeMm: 12.0,
  plSlotCount: 2,
  plSlotAngleOffsetDeg: 0,
  plSlotLengthManualMm: 30.0,
  plSlotStartZMm: 13.0,
  plClearanceLengthMm: 4.0,
  plSlotStartFromMainBarrelMm: 8.0,
  plPinDiameterMm: 2.0,
  plPinClearanceMm: 0.3,
  plAssemblyIncludeMainBarrelSection: true,
  plAssemblyIncludeMovingCarrier: true,
  plAssemblyIncludeGuidePins: true,
  plAssemblyFuseBarrelToPl: true,
  plImportedStlHeightMm: 9.0,
  plImportedStlFlipX: false,
  plImportedStlFlipY: false,
  plImportedStlFlipZ: false,
  plImportedStlRotateXDeg: 0,
  plImportedStlRotateYDeg: 0,
  plImportedStlRotateZDeg: 0,
  plImportedStlOffsetXMm: 0,
  plImportedStlOffsetYMm: 0,
  plImportedStlOffsetZMm: 0,
  plBarrelAttachZMm: 0.0,
  plReferenceOverlapMm: 2.0,
  cupToCarrierClearanceMm: 0.6,
  plFuseBarrelToReference: true
};

export const defaultTargetLook: TargetLook = {
  swirl: 5,
  glow: 5,
  warmth: 5,
  contrast: 5,
  sharpness: 5,
  flareChaos: 5,
  stopDownCleanup: 5,
  caControl: 5,
  facesOnThirdsUsable: 5
};

export function createEmptyMeasurementsState(nowIso = new Date().toISOString()): MeasurementsState {
  return {
    annotations: [],
    updatedAt: nowIso
  };
}

export function createDemoProject(): LensProject {
  const now = new Date().toISOString();
  return {
    id: "demo-helios-omit-50",
    name: "Helios Omit 50 Prototype",
    donorLens: "Helios 44-2",
    baseFocalLengthMm: 58,
    targetFormat: "FULL_FRAME",
    targetImageCircleMm: 46.3,
    targetMount: "PL",
    currentBuildVersion: "V1",
    notes:
      "Experimental Timo Sasaki / Omit-style prototype. Goal: vintage wide open, cleaner when stopped down.",
    targetLook: {
      swirl: 8,
      glow: 8,
      warmth: 7,
      contrast: 4,
      sharpness: 5,
      flareChaos: 7,
      stopDownCleanup: 9,
      caControl: 7,
      facesOnThirdsUsable: 7
    },
    cadDefaults: { ...defaultCadDefaults },
    createdAt: now,
    updatedAt: now,
    measurements: createEmptyMeasurementsState(now),
    focusTravel: defaultFocusTravelSetup(),
    mechanicalParts: [],
    stackItems: [
      {
        id: "e1",
        type: "glass",
        opticalType: "GLASS",
        name: "E1 front element",
        positionIndex: 0,
        diameterMm: 30.97,
        thicknessMm: 4.2,
        thicknessMeasurementType: "unknown",
        thicknessConfidence: "unknown",
        flipped: false,
        coatingColor: "amber/blue",
        glassUnknown: true,
        measuredConfidence: "medium"
      },
      {
        id: "spacer1",
        type: "spacer",
        opticalType: "SPACER",
        name: "Spacer / Air Gap Ring E1-E2",
        positionIndex: 1,
        innerDiameterMm: 28,
        outerDiameterMm: 38,
        thicknessMm: 5,
        desiredOpticalAirGapMm: 5,
        physicalSpacerThicknessMm: 5,
        physicalSpacerThicknessSource: "same_as_airspace",
        airspaceMeasurementType: "unknown",
        airspaceConfidence: "unknown",
        insertedItems: [],
        insertedItemsTotalThicknessMm: 0,
        autoFitToBarrel: true,
        hasAntiReflectionGrooves: false,
        chamferEnabled: false,
        chamferMm: 0.2
      },
      {
        id: "e2",
        type: "glass",
        opticalType: "GLASS",
        name: "E2 element",
        positionIndex: 2,
        diameterMm: 27.93,
        thicknessMm: 3.8,
        thicknessMeasurementType: "unknown",
        thicknessConfidence: "unknown",
        flipped: false,
        glassUnknown: true,
        measuredConfidence: "medium"
      },
      {
        id: "diff1",
        type: "diffusion",
        opticalType: "DIFFUSION",
        name: "Clear-center diffusion disk",
        positionIndex: 3,
        diskDiameterMm: 30,
        clearCenterDiameterMm: 12,
        diffusionOuterDiameterMm: 24,
        thicknessMm: 1,
        strengthLabel: "subtle",
        positionNotes:
          "Near iris. Wide open should include diffusion ring; stopped down should clean up."
      },
      {
        id: "iris1",
        type: "iris",
        opticalType: "IRIS",
        name: "Iris disk 14mm",
        positionIndex: 4,
        diskDiameterMm: 30,
        apertureDiameterMm: 14,
        thicknessMm: 1.2,
        isOval: false,
        tabEnabled: true,
        tabWidthMm: 6,
        tabLengthMm: 8
      },
      {
        id: "spacer2",
        type: "spacer",
        opticalType: "SPACER",
        name: "Spacer / Air Gap Ring iris-rear group",
        positionIndex: 5,
        innerDiameterMm: 24,
        outerDiameterMm: 38,
        thicknessMm: 12,
        desiredOpticalAirGapMm: 12,
        physicalSpacerThicknessMm: 12,
        physicalSpacerThicknessSource: "same_as_airspace",
        airspaceMeasurementType: "unknown",
        airspaceConfidence: "unknown",
        insertedItems: [],
        insertedItemsTotalThicknessMm: 0,
        autoFitToBarrel: true,
        hasAntiReflectionGrooves: false,
        chamferEnabled: false,
        chamferMm: 0.2
      },
      {
        id: "rear",
        type: "glass",
        opticalType: "GLASS",
        name: "Rear group E3/E4",
        positionIndex: 6,
        diameterMm: 26.43,
        thicknessMm: 15.8,
        thicknessMeasurementType: "unknown",
        thicknessConfidence: "unknown",
        flipped: false,
        glassUnknown: true,
        measuredConfidence: "medium"
      },
      {
        id: "mount",
        type: "mount",
        opticalType: "MOUNT",
        name: "PL mount placeholder",
        positionIndex: 7,
        mountType: "PL",
        flangeDistanceMm: 52,
        innerClearanceMm: 40
      }
    ],
    experiments: []
  };
}
